[package]
name = "gst-plugin-audionimbus"
version.workspace = true
edition.workspace = true
authors = ["Matthew Waters <matthew@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer plugin for audionimbus (Steam Audio)"
repository.workspace = true
rust-version.workspace = true

[dependencies]
gst = { workspace = true, features = ["v1_16"] }
gst-base = { workspace = true, features = ["v1_16"] }
gst-audio = { workspace = true, features = ["v1_16"] }

audionimbus = { version = "0.14.0", features = ["auto-install"] }

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[lib]
name = "gstaudionimbus"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = []

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0 >= 1.22, gstreamer-audio-1.0 >= 1.20, gobject-2.0, glib-2.0, gmodule-2.0"

