[package]
name = "gst-plugin-image"
edition.workspace = true
version.workspace = true
repository.workspace = true
rust-version.workspace = true
authors = ["Amyspark <amy@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer plugin based on image-rs"

[dependencies]
gst.workspace = true
gst-base.workspace = true
gst-video.workspace = true
image = { package = "image", version = "0.25.9", default-features = false, features = ["rayon", "nasm"] }
image_extras = { package = "image-extras", version = "0.1", default-features = false}
num-rational = { version = "0.4", default-features = false, features = [] }

[dev-dependencies]
gst-check.workspace = true

[lib]
name = "gstimagers"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
default = ["v1_24", "still_formats", "still_formats_extras", "animated_formats"]
static = []
capi = []
doc = []
still_formats = ["avif", "bmp", "dds", "exr", "ff", "hdr", "ico", "jpeg", "pnm", "qoi", "tga", "tiff"]
still_formats_extras = ["ora", "otb", "pcx", "sgi", "wbmp", "xbm", "xpm"]
# See anim/imp.rs -- add PNG and AVIF when upstream supports them
animated_formats = ["gif", "png", "webp"]
avif = ["image/avif"]
bmp = ["image/bmp"]
dds = ["image/dds"]
exr = ["image/exr"]
ff = ["image/ff"]
gif = ["image/gif"]
hdr = ["image/hdr"]
ico = ["image/ico"]
jpeg = ["image/jpeg"]
ora = ["image_extras/ora"]
otb = ["image_extras/otb"]
pcx = ["image_extras/pcx"]
png = ["image/png"]
pnm = ["image/pnm"]
qoi = ["image/qoi"]
sgi = ["image_extras/sgi"]
tga = ["image/tga"]
tiff = ["image/tiff"]
wbmp = ["image_extras/wbmp"]
webp = ["image/webp"]
xbm = ["image_extras/xbm"]
xpm = ["image_extras/xpm"]
v1_24 = ["gst-video/v1_24"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-video-1.0"
